drop table if exists equipment_rent_history cascade;
drop table if exists client cascade;
drop table if exists equipment cascade;
--drop table if exists equipment_rent_history_id;


CREATE TABLE if not exists client
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    adress VARCHAR(255),
    email  VARCHAR(255),
    phone  VARCHAR(255),
    CONSTRAINT pk_client PRIMARY KEY (id)
    );

CREATE TABLE if not exists equipment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type         VARCHAR(255),
    model        VARCHAR(255),
    name         VARCHAR(255),
    color        VARCHAR(255),
    size         VARCHAR(255),
    observations VARCHAR(255),
    brand        VARCHAR(255),
    img_url      VARCHAR(255),
    is_rented    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_equipment PRIMARY KEY (id)
    );

--CREATE TABLE if not exists equipment_rent_history_id
--(
--    equipment_id BIGINT,
--    rent_date    TIMESTAMP WITHOUT TIME ZONE
--);

--ALTER TABLE equipment_rent_history_id
--    ADD CONSTRAINT FK_EQUIPMENTRENTHISTORYID_ON_EQUIPMENT FOREIGN KEY (equipment_id) REFERENCES equipment (id);

CREATE TABLE if not exists equipment_rent_history
(
    devolution_predicted_date TIMESTAMP WITHOUT TIME ZONE,
    devolution_date           TIMESTAMP WITHOUT TIME ZONE,
    client_id                 BIGINT,
    observations              VARCHAR(255),
    equipment_id              BIGINT                      NOT NULL,
    rent_date                 TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_equipmentrenthistory PRIMARY KEY (equipment_id, rent_date)
    );

ALTER TABLE equipment_rent_history
    ADD CONSTRAINT FK_EQUIPMENTRENTHISTORY_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE equipment_rent_history
    ADD CONSTRAINT FK_EQUIPMENTRENTHISTORY_ON_EQUIPMENT FOREIGN KEY (equipment_id) REFERENCES equipment (id);


